INSERT INTO DNA (id,sequence, creation_date, created_by) VALUES (1,'5-GTATTACCCTAGTAATAGCGCCCGCTATGTACCACCTCTG-3', now(), 'americano2021');
INSERT INTO DNA (id,sequence, creation_date, created_by) VALUES (2,'5-CTAGTAATACCCTAGTACTATGTAAATAGCGCTATGGTAA-3', now(), 'benjamin');
INSERT INTO DNA (id,sequence, creation_date, created_by) VALUES (3,'5-CCGCTATACCCTTTACCCGTACCGTAAAGTAATGCGCT-3', now(), 'white' ); 

INSERT INTO PCR_PRIMER (id,sequence, creation_date, created_by) VALUES (1,'TRAV2 F1','5-CCGCTATACCCTTTACCCGTACCGTAAAGTAATGCGCT-3', now(), 'white' ); 
TRAV2 F1
 5'-AAGCAAGAGTGGTTGTTGCC-3' ChIP
TRAV2 R1
 5'-TCACTTTTGCCACCTGCTTC-3'
TRAV11 F1
 5'-TGGCTGTACTTCCTGAGAGTC-3'
TRAV11 R1
 5'-ATAATGCAGCCACAAGACCAC-3'
TRAV14 F1
 5'-AGCTGAGGTGCCTGTGAAGT-3'
TRAV14 R1
 5'-ACTCACCAGCTAGGTGAAGG-3'
TRAV15D-1 F1
 5'-AAGTAAGAGGCTGTGGTAAGCTCT-3'
TRAV15D-1 R1
 5'-TCTAAGTGCCTGCCACGTGT-3'
TRAV15D-2 F1
 5'-ATGCACACTGCCTGTCTCTC-3' 